amazon/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'amazon'

urlpatterns = [
    path('lp/', views.Lp.as_view(), name='lp'),
    path('items/', views.ItemList.as_view(), name='item_list'),
    path('items/<int:pk>', views.ItemDetail.as_view(), name='item_detail'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout', auth_view.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup/done/<token>', views.SignUpDone.as_view(), name='signup_done'),
    path('cart/<int:pk>', views.ShoppingCartDetail.as_view(), name='cart'),
    path('ajax_amount/', views.update_cart_item, name='update_cart_item_amount'),
    path('ajax_delete', views.delete_cart_item, name='delete_cart_item'),
]

ecsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('amazon/', include('amazon.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amazon/models.py
from django.db import models
from django import forms
# Create your models here.
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db.models import Sum, F, Avg
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class Product(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = '商品'

    thumbnail = models.ImageField(
        verbose_name='サムネイル',
        upload_to='thumbnails/',
    )

    name = models.CharField(
        verbose_name='名前',
        max_length=150,
        null=False,
        blank=False,
    )

    price = models.IntegerField(
        verbose_name='値段',
    )

    description = models.TextField(
        verbose_name='説明',
    )

    @property
    def avg_rating(self):
        return self.reviews.all().aggregate(avg_rating = Avg('rating'))['avg_rating'] or 0


class MyUserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = 'ユーザ'
        verbose_name_plural = 'ユーザ'

    """ユーザカスタムモデル"""
    email = models.EmailField('メールアドレス', max_length=150, null=False, blank=False, unique=True)
    name = models.CharField('名前', max_length=150, null=False, blank=False)

    is_staff = models.BooleanField(
        '管理者',
        default=False,
        help_text=_(
            'Designate whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        '有効',
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = MyUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email


class ShoppingCart(models.Model):

    user = models.OneToOneField(
        User,
        verbose_name='ユーザ',
        related_name='cart',
        on_delete=models.CASCADE
    )

    @property
    def item_count(self):
        return self.cart_items.all().aggregate(amount = Sum('amount'))['amount']

    @property
    def total_price(self):
        return self.cart_items.all().aggregate(total=Sum(F('product__price') * F('amount')))['total']


class ShoppingCartItem(models.Model):
    cart = models.ForeignKey(
        ShoppingCart,
        related_name='cart_items',
        verbose_name='ショッピングカート',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        verbose_name='商品',
        on_delete=models.CASCADE
    )
    amount = models.IntegerField(
        verbose_name='数量'
    )


class Review(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='ユーザ',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='reviews',
        verbose_name='商品',
        on_delete=models.CASCADE
    )
    rating = models.IntegerField(
        verbose_name='評価',
        default=0
    )
    title = models.CharField(
        verbose_name='タイトル',
        null=False,
        blank=False,
        max_length=255
    )
    comment = models.TextField(
        verbose_name='コメント',
        blank=False,
        null=False
    )

amazon/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from amazon.models import User, Review


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user', 'product', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
        self.fields['rating'].widget.attrs['style'] = 'display:none'

amazon/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import dumps, loads, SignatureExpired, BadSignature
from django.http import HttpResponseRedirect, HttpResponseBadRequest, JsonResponse
from django.template.loader import get_template
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.views.generic.edit import ModelFormMixin

from ecsite import settings
from .forms import LoginForm, SignUpForm, ReviewForm
from .models import Product, User, ShoppingCart, ShoppingCartItem


class Lp(TemplateView):
    template_name = 'amazon/lp.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items = Product.objects.all()
        context['items'] = items
        return context


class ItemList(ListView):
    model = Product
    template_name = 'amazon/item_list.html'

    def get_queryset(self):
        products = Product.objects.all()
        if 'q' in self.request.GET and self.request.GET['q'] is not None:
            q = self.request.GET['q']
            products = products.filter(name__icontains=q)
        return products


class ItemDetail(ModelFormMixin, DetailView):
    model = Product
    template_name = 'amazon/item_detail.html'
    form_class = ReviewForm

    def form_valid(self, form):
        review = form.save(commit=False)
        review.product = self.get_object()
        review.user = self.request.user
        review.save()
        return HttpResponseRedirect(self.request.path_info)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            self.object = self.get_object()
            return self.form_invalid(form)


class Login(LoginView):
    form_class = LoginForm
    template_name = 'amazon/login.html'


class SignUp(CreateView):
    """ユーザ仮登録"""
    template_name = 'amazon/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        "仮登録と本登録メールの発行"
        # 仮登録の段階ではis_activeをFalseにしておく(レコードは保存しておく)

        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }
        subject_template = get_template('amazon/mail_template/sign_up/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('amazon/mail_template/sign_up/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        messages.success(self.request, '本登録用リンクを送付しました')
        return HttpResponseRedirect(reverse('amazon:signup'))


class SignUpDone(TemplateView):
    """メール内URLアクセス後のユーザ本登録"""

    template_name = 'amazon/sign_up_done.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)

    def get(self, request, **kwargs):
        token = kwargs.get('token')

        try:
            user_pk = loads(token, max_age=self.timeout_seconds)
        except (SignatureExpired, BadSignature):
            return HttpResponseBadRequest()

        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save()

                    cart = ShoppingCart()
                    cart.user = user
                    cart.save()

                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class ShoppingCartDetail(LoginRequiredMixin, DetailView):
    model = ShoppingCart
    template_name = "amazon/shopping_cart.html"

    def post(self, request, *args, **kwargs):
        user = request.user
        product_pk = request.POST.get('product_pk')
        product = Product.objects.get(pk = product_pk)
        amount = request.POST.get('amount')

        exist = ShoppingCartItem.objects.filter(cart__user = user).filter(product = product)

        # すでにカートに存在する商品の場合は個数をインクリメント
        if len(exist) > 0:
            current_amount = exist[0].amount
            exist[0].amount = current_amount + int(amount)
            exist[0].save()
        else:
            new_cart_item = ShoppingCartItem()
            new_cart_item.cart = request.user.cart
            new_cart_item.product = product
            new_cart_item.amount = int(amount)
            new_cart_item.save()
        return HttpResponseRedirect(reverse('amazon:cart',  kwargs={'pk': self.get_object().pk}))


def update_cart_item(request):
    cart_item_pk = request.POST.get('cart_item_pk')
    new_amount = request.POST.get('amount')

    if cart_item_pk is None or new_amount is None:
        return JsonResponse({'error': 'invalid request'})
    if int(new_amount) <= 0:
        return JsonResponse({'error': 'amount must be getter than zero'})

    try:
        cart_item = ShoppingCartItem.objects.get(pk = cart_item_pk)
        cart_item.amount = int(new_amount)
        cart_item.save()
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'error': str(e.args)})


def delete_cart_item(request):
    cart_item_pk = request.POST.get('cart_item_pk')
    if cart_item_pk is None:
        return JsonResponse({'error': 'invalid parameter'})
    try:
        cart_item = ShoppingCartItem.objects.get(pk=cart_item_pk)
        cart_item.delete()
        return JsonResponse({'success': True})
    except Exception as e:
        return JsonResponse({'error': str(e.args)})

templates/amazon/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <title>techpit amazon</title>
    <body>
        <header class="section-header">
            <section class="header-main">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-3">
                        <a href="{% url 'amazon:lp' %}">
                            <div class="brand-wrap">
                                <img class="logo" src="{% static 'images/logo-dark.png' %}">
                                <h2 class="logo-text">Techpit amazon</h2>
                            </div> <!-- brand-wrap.// -->
                        </a>
                        </div>
                        <div class="col-lg-6 col-sm-6">
                            <form method= "get" action="{% url 'amazon:item_list' %}" class="search-wrap">
                                <div class="input-group">
                                    <input name="q" type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-append">
                                        <button id="id_search_button" class="btn btn-warning" type="submit">
                                        <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form> <!-- search-wrap .end// -->
                        </div> <!-- col.// -->
                        <div class="col-lg-3 col-sm-6">
                            <div class="widgets-wrap d-flex justify-content-end">
                                <!-- [7-5] ショッピングカート画面へのリンク追加 ここから -->
                                {% if user.is_authenticated %}
                                <div class="widget-header icontext">
                                    <a href="{% url 'amazon:cart' user.cart.pk %}" class="icontext">
                                        <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-shopping-cart"></i></div>
                                        <div class="text-wrap">
                                            <small>カート</small>
                                            <span>{{ user.cart.item_count|default_if_none:"0" }}商品</span>
                                        </div>
                                    </a>
                                </div> <!-- widget .// -->
                                {% endif %}
                                <!-- [7-5] ショッピングカート画面へのリンク追加 ここまで -->
                                <!-- [5-6] ログイン状態による分岐追加 ここから -->
                                <div class="widget-header icontext">
                                    <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-user"></i></div>
                                    <div class="text-wrap">
                                        {% if user.is_authenticated %}
                                        <small>{{user.name}}さん</small>
                                        <span><a href="{% url 'amazon:logout' %}">Logout</a></span>
                                        {% else %}
                                        <small>ゲスト</small>
                                        <span><a href="{% url 'amazon:login' %}">Login</a></span>
                                        {% endif %}
                                    </div>
                                </div> <!-- widget  dropdown.// -->
                                <!-- [5-6] ログイン状態による分岐追加 ここまで -->

                            </div>	<!-- widgets-wrap.// -->
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->
                </div> <!-- container.// -->
            </section> <!-- header-main .// -->
        </header> <!-- section-header.// -->
        <div class="container" style="padding: 2rem">
                {% block content %}{% endblock %}
        </div>
        <footer class="section-footer bg2">
            <div class="container">
                <section class="footer-bottom row">

                    <div class="col-sm-12">
                        <p class="text-sm-right">
        Copyright © 2019
        <a href="#">Techpit</a>
                        </p>
                    </div>
                </section> <!-- //footer-top -->
            </div><!-- //container -->
        </footer>
        <!-- [7-5] Ajax csrf対策追加 ここから -->
        <script type="text/javascript">
            function getCookie(name) {
               var cookieValue = null;
               if (document.cookie && document.cookie !== '') {
                   var cookies = document.cookie.split(';');
                   for (var i = 0; i < cookies.length; i++) {
                       var cookie = jQuery.trim(cookies[i]);
                       // Does this cookie string begin with the name we want?
                       if (cookie.substring(0, name.length + 1) === (name + '=')) {
                           cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                           break;
                       }
                   }
               }
               return cookieValue;
           }

           var csrftoken = getCookie('csrftoken');

           function csrfSafeMethod(method) {
               // these HTTP methods do not require CSRF protection
               return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
           }

           $.ajaxSetup({
               beforeSend: function (xhr, settings) {
                   if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                       xhr.setRequestHeader("X-CSRFToken", csrftoken);
                   }
               }
           });
       </script>
       <!-- [7-5] Ajax csrf対策追加 ここまで -->
         {% block scripts %}{% endblock %}
    </body>
</html>

templates/amazon/item_list.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <div class="row-sm">
    {% for object in object_list %}

        <div class="col-md-3">
            <figure class="card card-product">
                <div class="img-wrap"> <img src="{{ object.thumbnail.url }}"></div>
                    <figcaption class="info-wrap">
                        <h6 class="title "><a href="{% url 'amazon:item_detail' object.pk %}">{{ object.name }}</a></h6>

                        <div class="price-wrap">
                            <span class="price-new">{{ object.price }}円</span>
                        </div> <!-- price-wrap.// -->

                </figcaption>
            </figure> <!-- card // -->
        </div> <!-- col // -->

    {% endfor %}
    </div>
{% endblock %}

templates/amazon/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>
</head>
<body style="background: teal"">
    <div class="container" style="padding: 2rem">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-12">
                <div class="card bg-light">
                    <div class="card-body mx-auto">
                        <form action="" method="post">
                            {{ form.non_field_errors }}
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                </div>
                                {{ form.username }}
                            </div>
                            {{ form.email.errors }}

                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-lock"></i></span>
                                </div>
                                {{ form.password }}
                            </div>
                            {{ form.password.error }}
                            {% csrf_token %}
                            <div class="form-group">
                                <button type="submit" name="btn" value="Login" class="btn btn-primary btn-block">Login</button>
                            </div>
                            <!-- [6-6] サインアップ画面へのリンク追加 ここから -->
                            <p class="text-center">アカウントをお持ち出ないですか? <a href="{% url 'amazon:signup' %}">Sign up</a> </p>
                            <!-- [6-6] サインアップ画面へのリンク追加 ここまで -->
                        </form>
                    </div> <!-- card body -->
                </div> <!-- card  -->
            </div>
        </div>
    </div>
</body>

templates/amazon/shopping_cart.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}

{% if object.cart_items.all %}
 <div class="card shopping-cart">
    <div class="card-body">
        {% for cart_item in object.cart_items.all %}
        <div class="row">
            <div class="col-12 col-sm-12 col-md-2 text-center">
                    <img class="img-responsive" src="{{ cart_item.product.thumbnail.url }}" alt="prewiew" width="120" height="80">
            </div>
            <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                <h4 class="product-name"><strong>{{ cart_item.product.name }}</strong></h4>
                <h4>
                    <small>{{ cart_item.product.description }}</small>
                </h4>
            </div> <!-- col -->
            <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                    <h6><strong>{{ cart_item.product.price }} <span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-4 col-sm-4 col-md-4">
                    <div class="quantity">
                        <input name="amount" pk="{{ cart_item.pk }}" type="number" class="form-control" step="1" max="99" min="1" title="Qty" class="qty" size="4" value="{{ cart_item.amount }}">
                    </div>
                </div>
                <div class="col-2 col-sm-2 col-md-2 text-right">
                    <button name="delete" pk="{{ cart_item.pk }}" type="button" class="btn btn-outline-danger btn-xs">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                </div>
            </div> <!-- col -->
        </div> <!-- row -->
        {% endfor %}
        <hr>
    </div> <!-- card body -->
    <div class="card-footer">
        <a href="" class="btn btn-success pull-right">Checkout</a>
        <div class="float-right">Total price: <b> ¥{{ object.total_price }}</b></div>
    </div>
    </div> <!-- card footer -->
</div> <!-- card -->
{% else %}
<p>カートが空です</p>
{% endif %}
{% endblock %}

<!-- [7-5] Ajaxリクエスト部分追加 ここから -->
{% block scripts %}
<script>
    function call_update_amount(_pk, _amount) {
        return $.ajax({
            url: '{% url "amazon:update_cart_item_amount" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                cart_item_pk: _pk,
                amount: _amount
            }
        });
    }
    function call_delete_item(_pk) {
        return $.ajax({
            url: '{% url "amazon:delete_cart_item" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                cart_item_pk: _pk
            }
        });
    }

    $(function() {
        var $input_amount = $('input[name="amount"]');
        var $delete_button = $('button[name="delete"]');
        $input_amount.on('change', function() {
            var cart_item_pk = $(this).attr('pk');
            var new_amount = parseInt($(this).val());
            call_update_amount(cart_item_pk, new_amount)
            .done((data) => {
                if (data.success) {
                    location.reload();
                    return;
                }
                alert(data.error);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
        $delete_button.on('click', function() {
            var cart_item_pk = $(this).attr('pk');
            call_delete_item(cart_item_pk)
            .done((data) => {
                if (data.success) {
                    location.reload();
                    return;
                }
                alert(data.error);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
    })
</script>
{% endblock %}

templates/amazon/sign_up.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" >
    <title>title here</title>

</head>
<body style="background: #81D8D0">
    <div class="container" style="padding: 2rem">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-12">
                <div class="card bg-light">
                    <div class="card-body mx-auto">
                        <form method="POST" action="">
                            {{ form.non_field_errors }}
                            <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                            </ul>
                            {% csrf_token %}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                                    </div>
                                    {{ form.email }}

                            </div> <!-- form-group// -->
                            {{ form.email.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                                    </div>
                                    {{ form.name }}
                            </div> <!-- form-group// -->
                            {{ form.name.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                {{ form.password1 }}

                            </div> <!-- form-group// -->
                            {{ form.password1.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                {{ form.password2 }}

                            </div> <!-- form-group// -->
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
                            </div> <!-- form-group// -->
                            {{ form.password2.errors }}
                            <p class="text-center">アカウントをお持ちですか? <a href="{% url 'amazon:login' %}">Log In</a> </p>
                        </form>
                    </div>
                </div> <!-- card.// -->
            </div>
        </div>
    </div> <!-- container -->
</body>

templates/amazon/sign_up_done.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>

</head>
<body>
        <div class="jumbotron text-xs-center">
            <h1 class="display-3">Thank You!</h1>
                <p class="lead"><strong>Enjoy shopping!</strong> </p>
            <hr>
            <a class="btn btn-success" href="{% url 'amazon:login' %}">login</a>
        </div>

</body>
</html>